SELECT
	STATISTICS_META.ID,
	STATISTICS_META.STATISTIC_ID as stat_id,
	STATISTICS.STATE,
	STATISTICS.MEAN,
	STATISTICS.MIN,
	STATISTICS.MAX,
	STATISTICS_SHORT_TERM.STATE as shrt_state,
	STATISTICS_SHORT_TERM.MEAN as shrt_mean,
	STATISTICS_SHORT_TERM.MIN as shrt_min,
	STATISTICS_SHORT_TERM.MAX as shrt_max
FROM
	PUBLIC.STATISTICS_META
	LEFT JOIN STATISTICS ON STATISTICS_META.ID = STATISTICS.METADATA_ID
	LEFT JOIN STATISTICS_SHORT_TERM ON STATISTICS_META.ID = STATISTICS_SHORT_TERM.METADATA_ID
WHERE
	STATISTICS_META.STATISTIC_ID = 'sensor.invertor_battery_charging_power_kwh'
ORDER BY
	ID ASC