SELECT
	STATISTICS_META.ID,
	STATISTICS_META.STATISTIC_ID AS STAT_ID,
	STATISTICS_META.HAS_SUM,
	STATISTICS.STATE,
	STATISTICS.MEAN,
	STATISTICS.MIN,
	STATISTICS.MAX,
	STATISTICS.SUM,
	STATISTICS_SHORT_TERM.STATE AS SHRT_STATE,
	STATISTICS_SHORT_TERM.MEAN AS SHRT_MEAN,
	STATISTICS_SHORT_TERM.MIN AS SHRT_MIN,
	STATISTICS_SHORT_TERM.MAX AS SHRT_MAX,
	STATISTICS_SHORT_TERM.SUM AS SHRT_SUM
FROM
	PUBLIC.STATISTICS_META
	LEFT JOIN STATISTICS ON STATISTICS_META.ID = STATISTICS.METADATA_ID
	LEFT JOIN STATISTICS_SHORT_TERM ON STATISTICS_META.ID = STATISTICS_SHORT_TERM.METADATA_ID
WHERE
	STATISTICS_META.STATISTIC_ID IN (
		-- 'sensor.invertor_batteries_charging_monthly_kwh',
		'sensor.invertor_battery_charging_power_kwh'
	)