SELECT
	PUBLIC.STATES_META.METADATA_ID AS METADATA_ID,
	PUBLIC.STATES_META.ENTITY_ID AS META_ENTITY_ID,
	PUBLIC.STATES.STATE_ID,
	PUBLIC.STATES.STATE,
	PUBLIC.STATES.ENTITY_ID AS STATES_ENTITY_ID,
	PUBLIC.STATES.METADATA_ID AS STATES_METADATA_ID,
	PUBLIC.STATES.ATTRIBUTES_ID,
	PUBLIC.STATE_ATTRIBUTES.HASH,
	PUBLIC.STATE_ATTRIBUTES.shared_attrs
FROM
	PUBLIC.STATES_META
	LEFT JOIN STATES ON PUBLIC.STATES.METADATA_ID = PUBLIC.STATES_META.METADATA_ID
	LEFT JOIN STATE_ATTRIBUTES ON PUBLIC.STATE_ATTRIBUTES.ATTRIBUTES_ID = PUBLIC.STATES.ATTRIBUTES_ID
WHERE
	STATES_META.ENTITY_ID = 'sensor.invertor_battery_charging_power_kwh'

