# Common options for most devices I use

# NAMING
substitutions:
  name: "NAME-1"
  friendly_name: "Longer name with model info 1"

esphome:
  name: "NAME-1"
  friendly_name: "Longer name with model info 1"

##
# Here ADD board info
##

logger:
  level: INFO
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret fall_back_wifi_password
  reboot_timeout: 900s
  fast_connect: true

captive_portal:

web_server:
  port: 80
  version: 3
  sorting_groups:
  - id: sorting_group_diagnostic
    name: "Diagnostic info"
    sorting_weight: 60
  - id: sorting_group_service
    name: "Service"
    sorting_weight: 90

##
# Options of device
##

##
# Diagnostic sensors
##
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    web_server:
      sorting_group_id: sorting_group_diagnostic

  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
    web_server:
      sorting_group_id: sorting_group_diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      web_server:
        sorting_group_id: sorting_group_diagnostic
    ssid:
      name: "${friendly_name} SSID"
      web_server:
        sorting_group_id: sorting_group_diagnostic
    bssid:
      name: "${friendly_name} BSSID"
      web_server:
        sorting_group_id: sorting_group_diagnostic
    mac_address:
      name: "${friendly_name} Mac Wifi Address"
      web_server:
        sorting_group_id: sorting_group_diagnostic

##
# Service buttons
##

button:
- platform: restart
  name: "Restart"
  web_server:
    sorting_group_id: sorting_group_service

##
# END visible
##