# sudo vi /etc/asound.conf
# sudo alsactl restore

# Bathroom
pcm.usb_card_shower {
    type hw
    card USBCardShower
}

# Kitchen
pcm.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

# Bedroom
pcm.usb_card_bedroom {
    type hw
    card USBCardBedroom
}


# slave.pcm "hw:USBCard1"
pcm.kitchen_stereo{
  slave {
        pcm "usb_card_kitchen"
    }
    slave.channels 2
}

# slave.pcm "hw:USBCard1"
pcm.bathroom_mono{
  slave {
        pcm "usb_card_shower"
    }
  slave.channels 2
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}

# slave.pcm "hw:USBCard3"
pcm.bedroom_mono{
  slave {
        pcm "usb_card_bedroom"
    }
  slave.channels 2
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}
