#############################
# sudo vi /etc/asound.conf
# sudo alsactl restore
# sudo alsamixer
# sudo alsactl store
# aplay -l
# aplay -L | grep USBCard
#############################


####################################
######## USBCardShower ############
####################################
pcm.usb_card_shower {
    type hw
    card USBCardShower
}

ctl.usb_card_shower {
    type hw
    card USBCardShower
}

pcm.softvol_shower {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardShower
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_shower"
}


####################################
######## USBCardKitchen ############
####################################
pcm.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

ctl.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

pcm.softvol_kitchen {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardKitchen
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_kitchen"
}


####################################
######## USBCardBedroom ############
####################################
pcm.usb_card_bedroom {
    type hw
    card USBCardBedroom
}

ctl.usb_card_bedroom {
    type hw
    card USBCardBedroom
}

pcm.softvol_bedroom {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardBedroom
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_bedroom"
}
