#############################
# sudo vi /etc/asound.conf
# sudo alsactl --no-ucm restore
# sudo alsamixer
# sudo alsactl store
# aplay -l
# aplay -L | grep USBCard
#############################

### DEFAULT is bathroom
# It cannot be off
pcm.!default  {
    type hw 
    card USBCardShower
}

ctl.!default {
    type hw 
    card USBCardShower
}

####################################
######## USBCardKitchen ############
####################################
pcm.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

ctl.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

pcm.softvol_kitchen {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardKitchen
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_kitchen"
}


####################################
######## USBCardShower ############
####################################
pcm.usb_card_shower {
    type hw
    card USBCardShower
}

ctl.usb_card_shower {
    type hw
    card USBCardShower
}

pcm.softvol_shower {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardShower
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_shower"
}

# slave.pcm "hw:USBCard1"
# https://forums.pimoroni.com/t/phat-dac-mixing-stereo-to-mono-mpd-alsa/5453
pcm.bathroom_mono {
  slave.pcm usb_card_shower
  slave.channels 2
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}

# EXTRA
# pcm.dmixer {
#     type dmix
#     ipc_key 1024
#     slave {
#         pcm "usb_card_shower"
#         channels 2
#     }
#     ttable {
#         0.0 0.5
#         1.0 0.5
#         0.1 0
#         1.1 0
#     }
# }

ctl.bathroom_mono {
  type hw
  card USBCardShower
}

####################################
######## USBCardBedroom ############
####################################
pcm.usb_card_bedroom {
    type hw
    card USBCardBedroom
}

ctl.usb_card_bedroom {
    type hw
    card USBCardBedroom
}

pcm.softvol_bedroom {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardBedroom
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_bedroom"
}

# slave.pcm "hw:USBCard3"
# https://forums.pimoroni.com/t/phat-dac-mixing-stereo-to-mono-mpd-alsa/5453
pcm.bedroom_mono {
  slave.pcm usb_card_bedroom
  slave.channels 2
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}

# pcm.dmixer {
#     type dmix
#     ipc_key 1025
#     slave {
#         pcm "usb_card_bedroom"
#         channels 2
#     }
#     ttable {
#         0.0 0.5
#         1.0 0.5
#         0.1 0
#         1.1 0
#     }
# }

ctl.bedroom_mono {
  type hw
  card USBCardShower
}

####################################
######## All cards in ONE ##########
####################################