#############################
# sudo vi /etc/asound.conf
# sudo alsactl restore
# sudo alsamixer
# sudo alsactl store
# aplay -l
# aplay -L | grep USBCard
#############################


####################################
######## USBCardKitchen ############
####################################
pcm.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

ctl.usb_card_kitchen {
    type hw
    card USBCardKitchen
}

pcm.softvol_kitchen {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardKitchen
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_kitchen"
}

####################################
######## USBCardShower ############
####################################
pcm.usb_card_shower {
    type hw
    card USBCardShower
}

ctl.usb_card_shower {
    type hw
    card USBCardShower
}

pcm.softvol_shower {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardShower
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_shower"
}

# slave.pcm "hw:USBCard1"
pcm.bathroom_mono{
  slave {
        pcm "usb_card_shower"
    }
  slave.channels 2
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}

####################################
######## USBCardBedroom ############
####################################
pcm.usb_card_bedroom {
    type hw
    card USBCardBedroom
}

ctl.usb_card_bedroom {
    type hw
    card USBCardBedroom
}

pcm.softvol_bedroom {
    type softvol
    slave {
        pcm "dmix"
    }
    control {
        name "Master"
        card USBCardBedroom
    }
}

pcm.!default {
    type plug
    slave.pcm "softvol_bedroom"
}

# slave.pcm "hw:USBCard3"
pcm.bedroom_mono{
  slave {
        pcm "usb_card_bedroom"
    }
  slave.channels 2
  type route
  ttable {
    # Copy both input channels to output channel 0 (Left).
    0.0 0.5
    1.0 0.5
    # Send nothing to output channel 1 (Right).
    0.1 0
    1.1 0
  }
}

####################################
######## All cards in ONE ##########
####################################